"""add User model

Revision ID: 8111ef25bea2
Revises: 1383ebe32570
Create Date: 2025-04-18 01:44:19.339631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8111ef25bea2'
down_revision = '1383ebe32570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
